# -*- mode: ruby -*-
# vi: set ft=ruby :

# Include config
dir = File.dirname(File.expand_path(__FILE__))
require 'yaml'
configValues = YAML.load_file("#{dir}/config.yaml")

module OS
    def OS.is_windows
        (/cygwin|mswin|mingw|bccwin|wince|emx/ =~ RUBY_PLATFORM) != nil
    end
end

# NFS will be used for *nix and OSX hosts, if not disabled explicitly in config
use_nfs_for_synced_folders = !OS.is_windows && (configValues['use_nfs'] == 1)

Vagrant.configure("2") do |config|

  # Main settings
  config.vm.box = "semulia/magento2-dev"
  config.vm.box_check_update = true
  config.vm.network "private_network", ip: configValues['private_ip']

  # Sync folders settings
  if use_nfs_for_synced_folders
    config.vm.synced_folder "../html", "/var/www/html/",
    type: "nfs",
    mount_options: ['nolock', 'vers=3', 'tcp', 'fsc', 'rw', 'noatime']
  else
    config.vm.synced_folder "../html", "/var/www/html/",
    owner: "www-data", group: "www-data",
    mount_options: ["dmode=777,fmode=777"]
  end

  # Host manager plugin configuration
  if Vagrant.has_plugin?('vagrant-hostmanager')
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.manage_guest = true
    config.hostmanager.ignore_private_ip = false
    config.hostmanager.include_offline = true
    config.vm.define configValues['hostname'] do |node|
      node.vm.hostname = configValues['hostname']
      node.vm.network :private_network, ip: configValues['private_ip']
    end
  end
end
